name: Deploy HTML to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    environment: prochaine-tempete
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      TZ: America/Montreal

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Python Script to Generate HTML
      run: python -u prochaine-tempete.py 
    
    - name: Package and upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: ./output

    # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
